"""add profile table

Revision ID: 0fe9eeabffdb
Revises: 5087d3d4b9e1
Create Date: 2026-09-22 23:11:50.106991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fe9eeabffdb'
down_revision: Union[str, None] = '5087d3d4b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('cv_pdf_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
