"""add cover_image_url to blog_posts

Revision ID: c5f633de8520
Revises: 35d2e3097fd7
Create Date: 2026-09-23 01:32:34.818584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5f633de8520'
down_revision: Union[str, None] = '35d2e3097fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'cover_image_url')
    # ### end Alembic commands ###
